#!/usr/bin/env node
// build_materials.js - Generuje moduły JS z materiałów markdown Gemini:
//   Trygonometria/zadania_odpowiedzi_rozwiazania.md          -> www/js/data/material-trygonometria.js
//   "Geometria Analiityczna/zadania_odpowiedzi_rozwiazania.md" -> www/js/data/material-geometria-analityczna.js
// Uruchamianie: npm run build:materials  (po każdej aktualizacji plików .md)

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUT_DIR = path.join(ROOT, "android", "app", "src", "main", "assets", "www", "js", "data");

const MATERIALS = [
  {
    id: "trygonometria",
    src: path.join(ROOT, "Trygonometria", "zadania_odpowiedzi_rozwiazania.md")
  },
  {
    id: "geometria-analityczna",
    src: path.join(ROOT, "Geometria Analiityczna", "zadania_odpowiedzi_rozwiazania.md")
  }
];

fs.mkdirSync(OUT_DIR, { recursive: true });

for (const m of MATERIALS) {
  if (!fs.existsSync(m.src)) {
    console.error(`[build:materials] BRAK pliku źródłowego: ${m.src}`);
    process.exitCode = 1;
    continue;
  }
  const text = fs.readFileSync(m.src, "utf8");
  const out = `// AUTO-GENERATED by scripts/build_materials.js — nie edytuj ręcznie.
// Źródło: ${path.relative(ROOT, m.src)} (odśwież: npm run build:materials)
const MD = ${JSON.stringify(text)};
export default MD;
`;
  const outFile = path.join(OUT_DIR, `material-${m.id}.js`);
  fs.writeFileSync(outFile, out, "utf8");
  console.log(`[build:materials] ${m.id}: ${(text.length / 1024).toFixed(0)} kB -> ${path.relative(ROOT, outFile)}`);
}
