#!/usr/bin/env node
// convert_legacy_data.mjs - jednorazowa konwersja danych legacy (JS) do TS.
// Uruchamianie: node scripts/convert_legacy_data.mjs  (z katalogu repo)
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const LEGACY = path.resolve(ROOT, "legacy", "js", "data");
const OUT = path.resolve(ROOT, "src", "features", "trainer", "tryg");
fs.mkdirSync(OUT, { recursive: true });

const { SPECIAL_ANGLES } = await import(path.join(LEGACY, "angles.js"));
const { TASK_CATEGORIES, TASKS } = await import(path.join(LEGACY, "tasks.js"));

const header = (src) =>
  "// AUTO-GENERATED by scripts/convert_legacy_data.mjs z " + src +
  " — nie edytuj ręcznie.\n";

// Kąty specjalne
const anglesTs =
  header("legacy/js/data/angles.js") +
  "export interface SpecialAngle {\n" +
  "  deg: number;\n  radLatex: string;\n  radDecimal: number;\n  quadrant: string;\n" +
  "  sinLatex: string; sinVal: number | null;\n" +
  "  cosLatex: string; cosVal: number | null;\n" +
  "  tgLatex: string; tgVal: number | null;\n" +
  "  ctgLatex: string; ctgVal: number | null;\n" +
  "  wierszyk: string;\n}\n\n" +
  "export const SPECIAL_ANGLES: SpecialAngle[] = " +
  JSON.stringify(SPECIAL_ANGLES, null, 1) + ";\n";
fs.writeFileSync(path.join(OUT, "anglesData.ts"), anglesTs);

// Zadania (bank maturalny trenera)
const tasksTs =
  header("legacy/js/data/tasks.js") +
  "export interface TaskStep { [k: string]: unknown }\n\n" +
  "export interface LegacyTask {\n" +
  "  id: string;\n  section: string;\n  category: string;\n" +
  "  [k: string]: unknown;\n}\n\n" +
  "export const TASK_CATEGORIES = " + JSON.stringify(TASK_CATEGORIES, null, 1) + ";\n\n" +
  "export const TASKS: LegacyTask[] = " + JSON.stringify(TASKS, null, 1) + ";\n";
fs.writeFileSync(path.join(OUT, "tasksData.ts"), tasksTs);

console.log("[convert] angles:", SPECIAL_ANGLES.length, "tasks:", TASKS.length);
